<?php
ob_start();
ini_set('display_errors', 0);
error_reporting(0);

require_once dirname(__DIR__) . '/vendor/autoload.php';

if ($_SERVER['REQUEST_METHOD'] !== 'POST' || !isset($_POST['analysis_json'])) {
    http_response_code(400);
    exit;
}

$analysis = json_decode($_POST['analysis_json'], true);

$mpdf = new \Mpdf\Mpdf([
  'format' => 'A4',
  'margin_top' => 45,
  'margin_left' => 15,
  'margin_right' => 15,
  'margin_bottom' => 20,
  'default_font' => 'dejavusans'
]);

$logoPath = dirname(__DIR__) . '/assets/logo.png';

$logoBase64 = '';
if (file_exists($logoPath)) {
    $logoData = file_get_contents($logoPath);
    $logoBase64 = 'data:image/png;base64,' . base64_encode($logoData);
}

$mpdf->SetHTMLHeader("
<div style='
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 12px 0 10px 0;
  border-bottom: 2px solid #00b094;
  font-family: Arial, sans-serif;
'>

  <!-- LEFT: LOGO -->
  <div>
    <img src='$logoBase64' style='height:40px;'>
  </div>

  <!-- RIGHT: TITLE -->
  <div style='text-align:right;'>
    <div style='
      font-size:16px;
      font-weight:700;
      color:#00b094;
      line-height:1.2;
    '>
      Resume Analysis Report
    </div>
    <div style='
      font-size:10px;
      color:#6b7280;
      margin-top:2px;
    '>
      Generated by SkillVora
    </div>
  </div>

</div>
");



/* ---------------- EXECUTIVE SUMMARY ---------------- */
$score = $analysis['overallScore'];

if ($score >= 80) {
    $summary = "Your resume is strong and highly ATS-friendly. Only minor improvements are needed.";
} elseif ($score >= 60) {
    $summary = "Your resume is decent but has noticeable gaps that may reduce interview chances.";
} else {
    $summary = "Your resume requires significant improvement to pass ATS screening and recruiter review.";
}

/* ---------------- PDF STYLES ---------------- */
$html = "
<style>
body {
  font-family: Arial, sans-serif;
  color: #1f2937;
  background: #ffffff;
}

h2 {
  font-size: 18px;
  font-weight: 700;
  color: #0f172a;
  margin: 35px 0 18px;
  border-left: 5px solid #00b094;
  padding-left: 12px;
}

h3 {
  font-size: 14px;
  font-weight: 600;
  margin-bottom: 10px;
}

.section {
  background: #f9fafb;
  padding: 20px;
  border-radius: 14px;
  margin-bottom: 32px;
}

.box {
  background: #ffffff;
  padding: 16px 18px;
  border-radius: 10px;
  margin-bottom: 20px;
  box-shadow: 0 2px 8px rgba(0,0,0,0.08);
}

.good {
  color: #15803d;
  font-weight: 600;
}

.bad {
  color: #b91c1c;
  font-weight: 600;
}

.small {
  font-size: 12px;
  color: #6b7280;
}

.score-badge {
  display: inline-block;
  padding: 6px 14px;
  border-radius: 999px;
  background: #00b094;
  color: #ffffff;
  font-size: 14px;
  font-weight: 700;
}

.step {
  margin-bottom: 14px;
  font-size: 13px;
  background: #ecfeff;
  padding: 14px 16px;
  border-left: 6px solid #00b094;
  border-radius: 8px;
}
</style>
";

/* ---------------- OVERVIEW ---------------- */
$html .= "
<div class='section'>
  <h2>Overview</h2>

  <div class='box'>
    <p>
      <strong>Overall Score:</strong>
      <span class='score-badge'>{$analysis['overallScore']}/100</span>
    </p>

    <p><strong>Ranking:</strong> " . str_replace('_', ' ', $analysis['ranking']) . "</p>

    <p style='margin-top:12px;'>$summary</p>
  </div>
</div>
";

/* ---------------- ATS COMPATIBILITY ---------------- */
$html .= "
<div class='section'>
  <h2>ATS Compatibility</h2>

<div class='box'>
  <p><strong>ATS Score:</strong> {$analysis['atsScore']['score']} ({$analysis['atsScore']['quality']})</p>
  ";

    if (!empty($analysis['atsScore']['issues'])) {
        foreach ($analysis['atsScore']['issues'] as $issue) {
            $html .= "<p class='bad'>• $issue</p>";
        }
    } else {
        $html .= "<p class='good'>✓ No ATS issues detected</p>";
    }

$html .= "<p class='small'>ATS systems automatically scan resumes before recruiters review them.</p>";
$html .= "</div></div>";
$html .= "<hr style='border:none;border-top:1px solid #e5e7eb;margin:35px 0;'>";

/* ---------------- CONTENT QUALITY ---------------- */
$html .= "<pagebreak />";
$html .= "
<div class='section'>
  <h2>Content Quality Breakdown</h2>

<div class='box'>
  <p>Experience: {$analysis['content']['experienceScore']}%</p>
  <p>Skills: {$analysis['content']['skillsScore']}%</p>
  <p>Education: {$analysis['content']['educationScore']}%</p>
  <p>Achievements: {$analysis['content']['achievementsScore']}%</p>
  <p class='small'>
  ✓ {$analysis['content']['quantifiableResults']} quantified results<br>
  ✓ {$analysis['content']['actionVerbsUsed']} strong action verbs
  </p>
</div>
";
$html .= "</div></div>";

/* ---------------- SECTION COMPLETENESS ---------------- */
$html .= "<pagebreak />";
$html .= "
<div class='section'>
  <h2>Section Completeness</h2>

<div class='box'>";

$sectionNotes = [
  'experience' => 'Core section for recruiter evaluation',
  'education' => 'Academic background information',
  'skills' => 'Used by ATS to match job keywords',
  'projects' => 'Shows practical experience and applied skills',
  'certifications' => 'Supports professional credibility',
  'summary' => 'Provides quick overview for recruiters',
  'objective' => 'Clarifies career direction',
  'achievements' => 'Highlights measurable success',
  'awards' => 'Shows recognition and excellence',
  'publications' => 'Relevant for academic or research roles',
  'contactInfo' => 'Required for recruiter contact'
];

foreach ($analysis['sections'] as $section => $present) {
    if ($present) {
        $html .= "
          <p class='good'>
            " . ucfirst($section) . ": ✓ Present
          </p>
        ";
    } else {

    // PHP logic FIRST
    $note = $sectionNotes[$section] ?? 'Additional information section';

    // Then append HTML
    $html .= "
      <div style='
        margin-bottom:14px;
        padding:10px 12px;
        background:#fff;
        border-left:4px solid #f59e0b;
        border-radius:6px;
      '>
        <strong class='bad'>" . ucfirst($section) . ": ✗ Missing</strong><br>
        <span class='small'>¡ $note</span>
      </div>
    ";
    }
}


$html .= "</div></div>";
$html .= "<hr style='border:none;border-top:1px solid #e5e7eb;margin:35px 0;'>";

/* ---------------- STEP-BY-STEP GUIDE ---------------- */
$html .= "
<div class='section'>
  <h2>Step-by-Step Resume Fix Guide</h2>

  <p class='small' style='margin-bottom:16px;'>
    Follow the steps below in order. Completing earlier steps will improve later results.
  </p>

  <div class='box'>
";

$step = 1;

/* STEP 1 — ATS */
if ($analysis['atsScore']['score'] < 70) {
    $html .= "<p class='step'>STEP $step: Simplify formatting to improve ATS readability.</p>";
    $step++;
}

/* STEP 2 — Experience */
if (!$analysis['sections']['experience']) {
    $html .= "<p class='step'>STEP $step: Add a clear Experience section with roles, dates, and results.</p>";
    $step++;
}

/* STEP 3 — Missing Sections (GROUPED) */
$missingSections = [];

foreach ($analysis['sections'] as $section => $present) {
    if (!$present && $section !== 'experience' && $section !== 'contactInfo') {
        $missingSections[] = ucfirst($section);
    }
}

if (!empty($missingSections)) {
    $html .= "<p class='step'>STEP $step: Add the following missing resume sections:</p>";
    $html .= "<ul style='margin-left:20px; font-size:13px;'>";
    foreach ($missingSections as $sec) {
        $html .= "<li>$sec</li>";
    }
    $html .= "</ul>";
    $step++;
}

/* STEP 4 — Keywords */
if (!empty($analysis['keywords']['missingSkills'])) {
    $html .= "<p class='step'>STEP $step: Insert missing job-relevant keywords naturally into your resume.</p>";
    $step++;
}

/* STEP 5 — Achievements */
if ($analysis['content']['quantifiableResults'] < 3) {
    $html .= "<p class='step'>STEP $step: Rewrite bullet points to include measurable achievements (numbers, %, impact).</p>";
    $step++;
}

$html .= "<p class='small'>Focus on the steps above in order for maximum improvement.</p>";
$html .= "</div></div>";
$html .= "<hr style='border:none;border-top:1px solid #e5e7eb;margin:35px 0;'>";

if ($step === 1) {
    $html .= "
    <p class='step'>
      ✔ Your resume is already well-structured. Focus on tailoring it for each job application.
    </p>
    ";
}


/* ---------------- FOOTER ---------------- */
$html .= "<p class='small'>Generated by SkillVora • Resume Improvement System</p>";

ob_clean();
$mpdf->WriteHTML($html);
$mpdf->Output('SkillVora_Resume_Report.pdf', 'D');
exit;