// Add this script to your result.html or create a separate generate_report.js file
// Make sure jsPDF is loaded: <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>

function generatePDF(analysis) {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();
    
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 15;
    let y = 20;

    // Load logo image
    const logoImg = new Image();
    logoImg.src = '../assets/logo.png';
    
    // Wait for logo to load before generating PDF
    logoImg.onload = function() {
        generatePDFContent(doc, analysis, pageWidth, pageHeight, margin, logoImg);
    };
    
    // Fallback if logo fails to load
    logoImg.onerror = function() {
        generatePDFContent(doc, analysis, pageWidth, pageHeight, margin, null);
    };
}

function generatePDFContent(doc, analysis, pageWidth, pageHeight, margin, logoImg) {
    let y = 20;

    // Header
    doc.setFillColor(0, 176, 148);
    doc.rect(0, 0, pageWidth, 15, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.setFont(undefined, 'bold');
    doc.text('Resume Analysis Report', pageWidth / 2, 10, { align: 'center' });
    
    // Add "Generated By" text with logo
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(8);
    doc.setFont(undefined, 'normal');
    
    const generatedByText = 'Generated By';
    const textWidth = doc.getTextWidth(generatedByText);
    const startX = pageWidth - margin - 40; // Adjust position from right
    
    doc.text(generatedByText, startX, 23);
    
    if (logoImg) {
        // Add logo next to "Generated By" text
        doc.addImage(logoImg, 'PNG', startX + textWidth + 2, 18, 35, 7);
    } else {
        // Fallback text if logo doesn't load
        doc.text('SkillVora', startX + textWidth + 2, 23);
    }

    y = 35;

    // Executive Summary
    const score = analysis.overallScore;
    let summary;
    if (score >= 80) {
        summary = "Your resume is strong and highly ATS-friendly. Only minor improvements are needed.";
    } else if (score >= 60) {
        summary = "Your resume is decent but has noticeable gaps that may reduce interview chances.";
    } else {
        summary = "Your resume requires significant improvement to pass ATS screening and recruiter review.";
    }

    // Overview Section
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(0, 176, 148);
    doc.text('Overview', margin, y);
    y += 8;

    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.setFont(undefined, 'normal');
    doc.text(`Overall Score: ${analysis.overallScore}/100`, margin + 5, y);
    y += 6;
    doc.text(`Ranking: ${analysis.ranking.replace(/_/g, ' ')}`, margin + 5, y);
    y += 6;
    doc.setFontSize(9);
    const summaryLines = doc.splitTextToSize(summary, pageWidth - 2 * margin - 10);
    doc.text(summaryLines, margin + 5, y);
    y += summaryLines.length * 5 + 10;

    // ATS Compatibility
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(0, 176, 148);
    doc.text('ATS Compatibility', margin, y);
    y += 8;

    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.setFont(undefined, 'normal');
    doc.text(`ATS Score: ${analysis.atsScore.score} (${analysis.atsScore.quality})`, margin + 5, y);
    y += 7;

    if (analysis.atsScore.issues && analysis.atsScore.issues.length > 0) {
        doc.setTextColor(185, 28, 28);
        analysis.atsScore.issues.forEach(issue => {
            const lines = doc.splitTextToSize(`- ${issue}`, pageWidth - 2 * margin - 10);
            doc.text(lines, margin + 5, y);
            y += lines.length * 5;
        });
    } else {
        doc.setTextColor(21, 128, 61);
        doc.text('+ No ATS issues detected', margin + 5, y);
        y += 7;
    }

    doc.setTextColor(107, 114, 128);
    doc.setFontSize(8);
    doc.text('ATS systems automatically scan resumes before recruiters review them.', margin + 5, y);
    y += 10;

    // Content Quality
    if (y > pageHeight - 60) {
        doc.addPage();
        y = 20;
    }

    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(0, 176, 148);
    doc.text('Content Quality Breakdown', margin, y);
    y += 8;

    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.setFont(undefined, 'normal');
    doc.text(`Experience: ${analysis.content.experienceScore}%`, margin + 5, y);
    y += 6;
    doc.text(`Skills: ${analysis.content.skillsScore}%`, margin + 5, y);
    y += 6;
    doc.text(`Education: ${analysis.content.educationScore}%`, margin + 5, y);
    y += 6;
    doc.text(`Achievements: ${analysis.content.achievementsScore}%`, margin + 5, y);
    y += 8;

    doc.setFontSize(8);
    doc.setTextColor(107, 114, 128);
    doc.text(`+ ${analysis.content.quantifiableResults} quantified results`, margin + 5, y);
    y += 5;
    doc.text(`+ ${analysis.content.actionVerbsUsed} strong action verbs`, margin + 5, y);
    y += 12;

    // Keyword Analysis
    if (y > pageHeight - 60) {
        doc.addPage();
        y = 20;
    }

    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(0, 176, 148);
    doc.text('Keyword Analysis', margin, y);
    y += 8;

    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.setFont(undefined, 'normal');
    doc.text(`Keyword Match: ${analysis.keywords.matchScore}%`, margin + 5, y);
    y += 6;
    doc.text(`Industry Relevance: ${analysis.keywords.relevance}`, margin + 5, y);
    y += 8;

    if (analysis.keywords.foundSkills && analysis.keywords.foundSkills.length > 0) {
        doc.setFontSize(9);
        doc.setFont(undefined, 'bold');
        doc.text('Found Skills:', margin + 5, y);
        y += 5;
        doc.setFont(undefined, 'normal');
        doc.setFontSize(8);
        const foundSkills = analysis.keywords.foundSkills.join(', ');
        const foundLines = doc.splitTextToSize(foundSkills, pageWidth - 2 * margin - 10);
        doc.text(foundLines, margin + 5, y);
        y += foundLines.length * 4 + 6;
    }

    if (analysis.keywords.missingSkills && analysis.keywords.missingSkills.length > 0) {
        doc.setFontSize(9);
        doc.setFont(undefined, 'bold');
        doc.setTextColor(185, 28, 28);
        doc.text('Missing Keywords:', margin + 5, y);
        y += 5;
        doc.setFont(undefined, 'normal');
        doc.setFontSize(8);
        const missingSkills = analysis.keywords.missingSkills.join(', ');
        const missingLines = doc.splitTextToSize(missingSkills, pageWidth - 2 * margin - 10);
        doc.text(missingLines, margin + 5, y);
        y += missingLines.length * 4 + 8;
    }

    // Section Completeness
    if (y > pageHeight - 80) {
        doc.addPage();
        y = 20;
    }

    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(0, 176, 148);
    doc.text('Section Completeness', margin, y);
    y += 8;

    const sectionNotes = {
        experience: 'Core section for recruiter evaluation',
        education: 'Academic background information',
        skills: 'Used by ATS to match job keywords',
        projects: 'Shows practical experience and applied skills',
        certifications: 'Supports professional credibility',
        summary: 'Provides quick overview for recruiters',
        objective: 'Clarifies career direction',
        achievements: 'Highlights measurable success',
        awards: 'Shows recognition and excellence',
        publications: 'Relevant for academic or research roles',
        contactInfo: 'Required for recruiter contact'
    };

    doc.setFontSize(10);
    for (const [section, present] of Object.entries(analysis.sections)) {
        if (y > pageHeight - 20) {
            doc.addPage();
            y = 20;
        }

        const sectionName = section.charAt(0).toUpperCase() + section.slice(1);
        if (present) {
            doc.setTextColor(21, 128, 61);
            doc.text(`${sectionName}: + Present`, margin + 5, y);
            y += 6;
        } else {
            doc.setTextColor(185, 28, 28);
            doc.text(`${sectionName}: - Missing`, margin + 5, y);
            y += 5;
            doc.setFontSize(8);
            doc.setTextColor(107, 114, 128);
            const note = sectionNotes[section] || 'Additional information section';
            const noteLines = doc.splitTextToSize(`  ${note}`, pageWidth - 2 * margin - 10);
            doc.text(noteLines, margin + 5, y);
            y += noteLines.length * 4 + 2;
            doc.setFontSize(10);
        }
    }

    y += 6;

    // Step-by-Step Guide
    if (y > pageHeight - 60) {
        doc.addPage();
        y = 20;
    }

    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(0, 176, 148);
    doc.text('Step-by-Step Resume Fix Guide', margin, y);
    y += 8;

    doc.setFontSize(8);
    doc.setTextColor(107, 114, 128);
    doc.setFont(undefined, 'normal');
    doc.text('Follow the steps below in order. Completing earlier steps will improve later results.', margin + 5, y);
    y += 8;

    let step = 1;
    doc.setFontSize(9);
    doc.setTextColor(0, 0, 0);

    // Step 1 - ATS
    if (analysis.atsScore.score < 70) {
        if (y > pageHeight - 15) {
            doc.addPage();
            y = 20;
        }
        const stepText = doc.splitTextToSize(`STEP ${step}: Simplify formatting to improve ATS readability.`, pageWidth - 2 * margin - 10);
        doc.text(stepText, margin + 5, y);
        y += stepText.length * 5 + 3;
        step++;
    }

    // Step 2 - Experience
    if (!analysis.sections.experience) {
        if (y > pageHeight - 15) {
            doc.addPage();
            y = 20;
        }
        const stepText = doc.splitTextToSize(`STEP ${step}: Add a clear Experience section with roles, dates, and results.`, pageWidth - 2 * margin - 10);
        doc.text(stepText, margin + 5, y);
        y += stepText.length * 5 + 3;
        step++;
    }

    // Step 3 - Missing Sections
    const missingSections = [];
    for (const [section, present] of Object.entries(analysis.sections)) {
        if (!present && section !== 'experience' && section !== 'contactInfo') {
            missingSections.push(section.charAt(0).toUpperCase() + section.slice(1));
        }
    }

    if (missingSections.length > 0) {
        if (y > pageHeight - 30) {
            doc.addPage();
            y = 20;
        }
        doc.text(`STEP ${step}: Add the following missing resume sections:`, margin + 5, y);
        y += 5;
        missingSections.forEach(sec => {
            if (y > pageHeight - 10) {
                doc.addPage();
                y = 20;
            }
            doc.text(`  - ${sec}`, margin + 10, y);
            y += 5;
        });
        y += 3;
        step++;
    }

    // Step 4 - Keywords
    if (analysis.keywords.missingSkills && analysis.keywords.missingSkills.length > 0) {
        if (y > pageHeight - 15) {
            doc.addPage();
            y = 20;
        }
        const stepText = doc.splitTextToSize(`STEP ${step}: Insert missing job-relevant keywords naturally into your resume.`, pageWidth - 2 * margin - 10);
        doc.text(stepText, margin + 5, y);
        y += stepText.length * 5 + 3;
        step++;
    }

    // Step 5 - Achievements
    if (analysis.content.quantifiableResults < 3) {
        if (y > pageHeight - 15) {
            doc.addPage();
            y = 20;
        }
        const stepText = doc.splitTextToSize(`STEP ${step}: Rewrite bullet points to include measurable achievements (numbers, %, impact).`, pageWidth - 2 * margin - 10);
        doc.text(stepText, margin + 5, y);
        y += stepText.length * 5 + 3;
        step++;
    }

    if (step === 1) {
        doc.text('+ Your resume is already well-structured. Focus on tailoring it for each job application.', margin + 5, y);
        y += 8;
    }

    doc.setFontSize(8);
    doc.setTextColor(107, 114, 128);
    doc.text('Focus on the steps above in order for maximum improvement.', margin + 5, y);
    y += 10;

    // Recommendations
    if (analysis.recommendations) {
        if (y > pageHeight - 60) {
            doc.addPage();
            y = 20;
        }

        if (analysis.recommendations.critical && analysis.recommendations.critical.length > 0) {
            doc.setFontSize(14);
            doc.setFont(undefined, 'bold');
            doc.setTextColor(220, 38, 38);
            doc.text('Critical Improvements', margin, y);
            y += 8;

            doc.setFontSize(9);
            doc.setFont(undefined, 'normal');
            doc.setTextColor(0, 0, 0);
            analysis.recommendations.critical.forEach(rec => {
                if (y > pageHeight - 15) {
                    doc.addPage();
                    y = 20;
                }
                const recLines = doc.splitTextToSize(`- ${rec}`, pageWidth - 2 * margin - 10);
                doc.text(recLines, margin + 5, y);
                y += recLines.length * 5 + 2;
            });
            y += 6;
        }

        if (analysis.recommendations.important && analysis.recommendations.important.length > 0) {
            if (y > pageHeight - 40) {
                doc.addPage();
                y = 20;
            }

            doc.setFontSize(14);
            doc.setFont(undefined, 'bold');
            doc.setTextColor(245, 158, 11);
            doc.text('Important Improvements', margin, y);
            y += 8;

            doc.setFontSize(9);
            doc.setFont(undefined, 'normal');
            doc.setTextColor(0, 0, 0);
            analysis.recommendations.important.forEach(rec => {
                if (y > pageHeight - 15) {
                    doc.addPage();
                    y = 20;
                }
                const recLines = doc.splitTextToSize(`- ${rec}`, pageWidth - 2 * margin - 10);
                doc.text(recLines, margin + 5, y);
                y += recLines.length * 5 + 2;
            });
            y += 6;
        }
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(107, 114, 128);
    doc.text('Generated by SkillVora - Resume Improvement System', margin, pageHeight - 10);

    // Save PDF
    doc.save('SkillVora_Resume_Report.pdf');
}

// Update the download button event listener
document.getElementById("downloadPdf").addEventListener("click", () => {
    const analysisData = sessionStorage.getItem("analysis");

    if (!analysisData) {
        alert("No analysis data found.");
        return;
    }

    try {
        const analysis = JSON.parse(analysisData);
        generatePDF(analysis);
    } catch (error) {
        console.error("Error generating PDF:", error);
        alert("Failed to generate PDF. Please try again.");
    }
});